baseURL = "https://bhushan.codes/"
languageCode = "en-us"
title = "Bhushan"
googleAnalytics = ""

[params]
    author = "Bhushan Khanale"
    description = "Developer + Competitive Programmer"
    githubUsername = "bkhanale"
    accent = "black"
    showBorder = false
    backgroundColor = "white"
    font = "Roboto Mono" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["C/C++", "Python", "Java", "Go", "Julia"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:bkhanale@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/bkhanale/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/BhushanKhanale/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/bhushan-khanale/"
    name = "linkedin"
    weight = 4
